using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace Sukiya.UI
{
    public partial class uc_XemDoanhThu : UserControl
    {
        public uc_XemDoanhThu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sukiya.Models.SukiyaContextDB dbContext = new Sukiya.Models.SukiyaContextDB();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.HoaDon.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.HoaDon.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
